### ISSUE TITLE
docker mac error

### ISSUE THREAD

**Issue by DanielAmsel** [microPIECE-team/microPIECE#41]
```
##############################################
############## REGRESSION TESTS ##############
##############################################

Running 'Binning test BED ztnbr'...                         [passed] 
Running 'Binning test BED ztnbr pre-binned'...              [passed] 
Running 'Binning test BED'...                               [passed] 
Running 'Binning test BED pre-binned'...                    [passed] 
Running 'Simple ZTNB Test 1'...                             [passed] 
Running 'Simple ZTNB Test 1, default sig.'...               [passed] 
Running 'Simple ZTNB Test 2, corrected pvals'...            [passed] 
Running 'Simple ZTNB Test 2'...                             [passed] 
Running 'Simple ZTNB Test 3'...                             [passed] 
Running 'Simple NB Test'...                                 [passed] 
Running 'Simple Poisson Test 1'...                          [passed] 
Running 'Simple Poisson Test 2'...                          [exec..]
Traceback (most recent call last):
  File "runRegressionTests.py", line 149, in <module>
    runTests(sys.argv[1])
  File "runRegressionTests.py", line 140, in runTests
    runTest(test, colWidth, logbuffer)
  File "runRegressionTests.py", line 103, in runTest
    os.wait()
OSError: [Errno 10] No child processes
make[2]: *** [test] Error 1
Makefile:179: recipe for target 'test' failed
make[2]: Leaving directory '/opt/piranha-1.2.1/src/test'
Makefile:37: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/opt/piranha-1.2.1/src'
Makefile:34: recipe for target 'test' failed
make: *** [test] Error 2
The command '/bin/sh -c apt update && apt install --yes --no-install-recommends bamtools libgsl-dev &&     wget http://smithlabresearch.org/downloads/piranha-1.2.1.tar.gz &&     tar xzf piranha-1.2.1.tar.gz &&     cd piranha-1.2.1 &&     ./configure &&     make all &&     make test &&     make install &&     cd /opt && rm -rf piranha-1.2.1.tar.gz /var/lib/apt/lists/*' returned a non-zero code: 2
```

**Comment by DanielAmsel** [comment]
Still an issue with the novel Docker `Version 17.12.0-ce-mac55 (23011)`
