### ISSUE TITLE
miraligner fails

### ISSUE THREAD

**Issue by greatfireball** [microPIECE-team/microPIECE#97]
```
Error calling command: java -jarmiraligner.jar -sub 1 -trim 3 -add 3 -s tca -freq -i [...] -db [...] -o [...]

STDERR: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
        at miraligner.map.align3end(map.java:445)
        at miraligner.map.align2(map.java:422)
        at miraligner.map.readseq(map.java:198)
        at miraligner.Main.main(Main.java:85)
```

**Comment by greatfireball** [comment]
@DanielAmsel found similar issues on github:
* https://github.com/lpantano/seqcluster/issues/18
* https://github.com/bcbio/bcbio-nextgen/issues/1357
The problem seems to be caused by the installed jre. Currently we are using 1.8, but should downgrade to 1.7, due to no available `miraligner.jar` solves that issue.

**Comment by greatfireball** [comment]
Nevertheless, we @DanielAmsel pointed onto another issue which might cause trouble #98

**Comment by greatfireball** [comment]
This issue need to be solved in the basecontainer
